export const styles = {
  container: {
    minHeight: 'calc(100vh - 68px)',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  flexContainer: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '100%',
    // justifyContent: 'center',
    alignItems: 'center',
    overflow: 'auto',
    padding: '0 8px',
  },
  square: {
    backgroundColor: '#B6D7A8',
    flexBasis: 'calc(33.33% - 16px)',
    maxWidth: 'calc(33.33% - 16px)',
    paddingTop: 'calc(33.33% - 16px)',
    position: 'relative',
    margin: '8px',
    overflow: 'hidden',
    '@media (min-width: 600px) and (max-width: 959px)': {
      flexBasis: 'calc(50% - 16px)',
      maxWidth: 'calc(50% - 16px)',
      paddingTop: 'calc(50% - 16px)',
    },
    '@media (min-width: 960px)': {
      flexBasis: 'calc(25% - 16px)',
      maxWidth: 'calc(25% - 16px)',
      paddingTop: 'calc(25% - 16px)',
    },
  },
  textContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
    width: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  notificationButton: {
    position: 'absolute',
    top: 8,
    right: 8,
  },
  pageContainer: {
    paddingTop: '30px',
    paddingBottom: '30px',
  },
  squareText: {
    textAlign: 'center',
    marginBottom: '20px',
    fontSize: '24px',
    fontWeight: 'bold',
  },
  title: {
    marginBottom: '1.5rem',
  },
};
